name: Main Workflow

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main, develop ]

jobs:
  static-cpp-msvc-2022-x64:
    name: 'Static C++ (MSVC 2022 x64)'
    uses: HBK-MicroStrain-Internal/workflows/.github/workflows/msvc-2022-x64.yml@main
    with:
      job_name: 'Static C++'
      debug: true
      release: true
      configure_preset: 'tests'
      build_preset: 'static'
      unit_test: true
      unit_test_preset: 'tests'
      check_auto: true
      package_preset: 'static'
      artifact_match_pattern: '*MSCL-Cpp*.zip'
